# services:
#   web:
#     build: .
#     image: cedricrabarijohn/test5
#     container_name: test5-container
#     command: python manage.py runserver 0.0.0.0:8000
#     ports:
#       - 8000:8000
#     depends_on:
#       - db
#     volumes: 
#       - .:/code

#   db:
#     image: postgres:14.1-alpine
#     container_name: db-container
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     ports:
#       - 5432:5432
#     volumes:
#       - ./db:/var/lib/postgresql/data

services:
  web:
    build: .
    image: cedricrabarijohn/test5
    container_name: test5-container
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/project
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    container_name: db-container
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data


# services:
#   db:
#     image: postgres
#     volumes:
#       - ./data/db:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#   web:
#     build: .
#     image: cedricrabarijohn/test5
#     container_name: test5-container
#     command: python manage.py runserver 0.0.0.0:8000
#     ports:
#       - 8000:8000
#     volumes:
#       - .:/code
#     depends_on:
#       - db
  # web:
  #   build: .
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - POSTGRES_NAME=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   depends_on:
  #     - db